# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev/

version: '3'

tasks:
  default:
    # desc: を書かないことで自分を一覧に出力しない
    summary: |
      デフォルトでタスクの一覧出力
    cmd: task --list --sort alphanumeric
    silent: true
    aliases:
      - ls

  summary:
    desc: view summary of all tasks
    summary: |
      全タスクのサマリー出力
    aliases:
      - la
    cmd: task --list-all --sort alphanumeric -j | jq -cr ".tasks[].name" | xargs -i sh -c 'task --summary {}; echo "\n---\n"'
    silent: true
    dir: '{{.USER_WORKING_DIR}}'
