# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev/

version: '3'

tasks:
  default:
    desc: list all tasks
    cmds:
      - task --list-all
    silent: true

  aqua-update:
    desc: Run aqua update, install, list for globally
    aliases:
      - a
    dir: ~/.config/aqua
    dotenv:
      - .env
    cmds:
      - echo "use github token [${GITHUB_TOKEN:0:20}***]"
      - aqua update
      - aqua install -all
      - aqua list --installed --all | sort


  # 以下 task のテストいろいろ
  test_all:
    desc: all test tasks
    aliases:
      - "t"
    cmds:
      - task: test_vars
        vars:
          TEST: $(date -Isec)
      - task: test_bool

  test_vars:
    desc: test about variables
    vars:
      TEST: $(date -I)
    cmds:
      - echo "now {{.TEST}}"

  test_bool:
    desc: test about bool vars
    vars:
      BOOL: true
    cmds:
      - echo {{.BOOL}}
      - echo ".BOOL" {{if .BOOL}}真{{else}}偽{{end}}

  test_variables:
    desc: test variables
    aliases:
      - tv
    vars:
      INT: 10
      FLOAT: 3.14
      ARRAY:
        - 1
        - 2
        - 3
      LIST:
        - A
        - B
        - C
      STRING: "日本語"
      RESULT: $(date -I)
    cmds:
      - echo {{add .INT .FLOAT}}
      - echo {{range .ARRAY}}{{.}}{{end}}
      - for:
          var: ARRAY
        cmd: echo "in " {{.ITEM}}
      - echo {{range .LIST}}{{.}}{{end}}
      - for:
          var: LIST
        cmd: echo "LIST has " {{.ITEM}}
        # LIST と ARRAY の違いとは
